In [85]:
# Dependencies and Setup
import numpy as np
from pandas import *

# File to Load
cities_data_to_load = 'Resources/cities.csv'

# Read School and Student Data File and store into Pandas Data Frames
cities_data_csv = pd.read_csv(cities_data_to_load)
#cities_data_csv.set_index('City_ID')

In [83]:
#Convert to DataFrame
Cities_Data_DF = pd.DataFrame(cities_data_csv)

Cities_Data_Clean = Cities_Data_DF.set_index('City_ID')

Cities_Data_Clean.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
City_ID,,,,,,,,,
0,leningradskiy,81,RU,1571175494,83,69.38,178.42,35.042,6.385
1,aklavik,90,CA,1571175494,85,68.22,-135.01,19.400,4.600
2,rikitea,1,PF,1571175494,87,-23.12,-134.97,74.354,3.726
3,ponta do sol,90,BR,1571175495,44,-20.63,-46.00,79.844,1.287
4,ushuaia,14,AR,1571175331,53,-54.81,-68.31,51.800,0.840

In [88]:
Cities_Data_DF.to_html('Cities_Data_HTML', index=False)